# Generated by Django 5.0.4 on 2024-04-25 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_invited_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
