# Generated by Django 5.0.4 on 2024-04-25 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='xxxxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_password_reset',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
