# Generated by Django 5.0.4 on 2024-04-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_invited_users'),
        ('doc', '0002_alter_doc_company_alter_doc_created_by'),
        ('user', '0002_remove_userprofile_companies_remove_userprofile_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='company.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='docs',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='doc.doc'),
        ),
    ]
